### ISSUE TITLE
`toSvg` rendering broken

### ISSUE THREAD

**Issue by uebayasi** [pablohirafuji/elm-qrcode#13]
`toImage` works for me, `toSvg` does not.

(I'll take a closer look at the SVG renderer code later, but not now.)

**Comment by pablohirafuji** [comment]
Could you post an image and tell me what OS and browser are you using? I would be happy to take a closer look.

**Comment by pablohirafuji** [comment]
Released on [3.3.1](https://package.elm-lang.org/packages/pablohirafuji/elm-qrcode/latest/QRCode).
