### ISSUE TITLE
Generate transparent image

### ISSUE THREAD

**Issue by viktorstrate** [pablohirafuji/elm-qrcode#24]
Hi, thank you for making this great little library.

Is there a way to generate a PNG image with a transparent background?

**Comment by pablohirafuji** [comment]
Hi, you are welcome.

Yes, you can specify a transparent background color, eg.:

```elm
QRCode.toImageWithOptions
    { moduleSize = 5
    , darkColor = 0xFF
    , lightColor = 0xFFFFFF00
    , quietZoneSize = 4
    }
    qrCode
```

**Comment by viktorstrate** [comment]
Got it, thank you. It even says so in the documentation :)
